# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'presenttime' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for presenttime
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'


  target 'presenttimeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'presenttime-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for presenttime-tvOS

  target 'presenttime-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
